spring:
  application:
    name: ms-eurekaserver
    
  security:
    user:
      name: admin
      password: 123456

server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false